### ISSUE TITLE
I tried to play a note like in the sample code

### ISSUE THREAD

**Issue by john02813** [cotejp/webmidi#12]
```html
<!DOCTYPE html>
<html>
<head>
	<title>oscillator.js</title>
	<script src="http://localhost/webmidi/webmidi.min.js"></script>
</head>
<body>
<script type="text/javascript">
WebMidi.enable( function() {
    WebMidi.playNote("C3", 1, 1000, WebMidi.outputs[0], 3);
  }, 
  function(error) {
    console.log("Could not enable WebMidi.");
  });

</script>
</body>
</html>
```
What am I missing?

**Comment by cotejp** [comment]
Some parts of WebMidi.js changed with the release of version 2. The code you are using was valid for version 1 but does not work in version 2. Here is what you need:

```javascript
WebMidi.enable(function(err) {

  if (err) {
    console.log("Could not enable WebMidi.");
  }

  WebMidi.outputs[0].playNote("C3", 3, {duration: 1000});

);
```

**Comment by john02813** [comment]
Hello I tried the revised code and it didn’t work either.
I have the latest version of webmidi.js on my hard drive in C:\inetpub\wwwroot\webmidi\.
Is there a subdirectory or a different name with .js on it that I should attach as a src=?
<!DOCTYPE html>
<html>
<head>
    <title>oscillator.js</title>
    <script src="http://localhost/webmidi/webmidi.min.js"></script>
</head>
<body>
<script type="text/javascript">

WebMidi.enable(function(err) {
  if (err) {
    console.log("Could not enable WebMidi.");
  }
  WebMidi.outputs[0].playNote("C3", 3, {duration: 1000});
);
</script>
</body>
</html>

**Comment by cotejp** [comment]
You will have to do a bit of troubleshooting on your end. I know nothing about your environment. Make sure the library is properly linked. You can do that by checking the **Network** pane of the development tools in your browser. Then, make sure the callback triggers properly by adding a `console.log("Works!")` statement in your script and checking in the browser's console if you can see it.

**Comment by john02813** [comment]
I give up. I have no idea as to what I am doing.

**Comment by mattHorrigan** [comment]
I have the same problem.  If I use the example setup code for outputting to another midi device, I always get something like "Uncaught TypeError: Cannot read property 'playNote' of undefined."  This is despite WebMIDI initially saying that it has initialized fine.  I am running Chrome, latest version.

**Comment by mattHorrigan** [comment]
Update: I have it working under certain circumstances.  Will report what I find once I have it narrowed down.
