### ISSUE TITLE
Firefox v52+

### ISSUE THREAD

**Issue by jazz-soft** [cotejp/webmidi#16]
Hi!
Just wanted to mention that the current version of WebMIDIAPIShim does not work in Firefox v.52+.
Though there is a jazz-midi extension for Firefox, it's API is different from Jazz-Plugin and it will require quite a lot of JavaScript coding for the workaround. You can see some of that code in JZZ.js

**Comment by cotejp** [comment]
Ok, thanks for informing me. Do you happen to know if there is ongoing work towards updating WebMIDIAPIShim to work with the jazz-midi extension?

I'll leave this issue open until I know more.

**Comment by jazz-soft** [comment]
I don't think Chris or anyone else involved have immediate plans for that.
Perhaps, everyone is just waiting Mozilla to implement WebMIDI API in Firefox, that will make WebMIDIAPIShim mostly obsolete.
Of course, you are more than welcome to make fixes in WebMIDIAPIShim :)

**Comment by cotejp** [comment]
Obviously, having native support would be ideal. Work on the Web MIDI API [has started](https://bugzilla.mozilla.org/show_bug.cgi?id=836897) but no target date has been set yet.

**Comment by cotejp** [comment]
The [documentation](https://github.com/cotejp/webmidi#user-content-browser-support) has been updated to reflect the current situation. I guess we'll have to wait for Mozilla to implement the native Web MIDI API...

**Comment by cotejp** [comment]
Jazz-Soft released a new [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/web-midi-api/) which solves this problem. I've done a little testing and it seems to be working with WebMidi.js.
