### ISSUE TITLE
Use `import` or `require` syntax for node module.

### ISSUE THREAD

**Issue by kevinchau321** [cotejp/webmidi#17]
Hi, I am building an application with React and Webpack, and I used NPM to install `webmidi`. 

I see from the README that I need to include a <script> tag:
```
<script src="node_modules/webmidi/webmidi.min.js"></script>
```

Is there a way to do this in javascript via an `import` or `require` statement?

**Comment by kevinchau321** [comment]
This statement worked for me:
```
import WebMidi from 'webmidi';
```
then I can enable WebMidi like usual:
```
    WebMidi.enable(function (err) {
      if (err) {
        console.log("WebMidi could not be enabled.", err);
      } else {
        console.log("WebMidi enabled!");
      }
    });
```

Is this the correct way to import WebMidi? Haven't had time to fully test it out, but I'm still new to node so any tips would help! 

P.S.: if this is the right way to use WebMidi with NPM, perhaps the README should be updated?

**Comment by cotejp** [comment]
> P.S.: if this is the right way to use WebMidi with NPM, perhaps the README should be updated?

@kevinchau321 That's a good idea. README now mentions it. Thanks.
