### ISSUE TITLE
connect to the bluetooth

### ISSUE THREAD

**Issue by Wingoc** [cotejp/webmidi#21]
When I use the Macbook to conect the bluetooth MIDI, then I open the browser and connect the webmidi.
Just like the code below:
	function Connect(){
		WebMidi.enable(function (err) {
			if (err) {
				console.log("WebMidi could not be enabled.", err);
			} else {
				console.log(WebMidi.sysexEnabled);
				output = WebMidi.outputs[0];
                                ......
Finally,I had connected the bluetooth device successfully. Also I could communicate wite the bluetooth device by use the Webmidi.js. However, when I send a Sysex messsge or a Note on or Note off message to the bluetooth device. And the I found the message send out pass through the bluetooth adapter will insert an unanticipated message code. 
Just like : if i send a Sysex message [0xf0 0x01 0x02 0x03 0xf7], Actually i will receive hte message is [0xf0 0x01 0x02 0x03 0xfa 0xf7] or [0xf0 0x01 0x02 0x03 0xfc 0xf7] or others;

For more information, please check my source code：https://github.com/Wingoc/BLE_USBMIDI
Thank you.

**Comment by cotejp** [comment]
Can you reply with a short bare code example that reproduces the problem?

**Comment by cotejp** [comment]
If you ever have time to send a short code sample that reproduces the problem, simply reopen the issue. For now, I'm going to close it.
