### ISSUE TITLE
Detecting chords using WebMIDI

### ISSUE THREAD

**Issue by antonioaguilar** [cotejp/webmidi#25]
I have a general question. How would you detect a chord using WebMIDI? From what I read in the API docs, you can use the ```noteon```  for single note/key events. If I want to detect a chord event, say when 3 or more notes are played together. Do I have to detect separate events for each note?  Any suggestions?

**Comment by cotejp** [comment]
There is nothing in the library to let you do that automatically. You would have to listen for `noteon` events triggered within a certain time frame. Or, you could also save the state of all notes in your app. This way, when a `noteon` is triggered you could check if other notes are currently played.
