### ISSUE TITLE
WebMidi.enable() callback never invoked

### ISSUE THREAD

**Issue by belm0** [cotejp/webmidi#28]
I'm trying to debug odd behavior when using webmidi and the iOS Web MIDI Browser.

If I connect my MIDI input device (happens to be bluetooth) after starting the app, webmidi behaves as expected.  However if I start the app with the MIDI device already connected, WebMidi.enable() never invokes its callback function.

It's hard to debug since the Safari remote inspector isn't working for me (Web MIDI Browser author claims it should), but I've confirmed that a JS exception is not occurring.  Roughly, the following code will only log "done":

```
WebMidi.enable(function(err) { log('enable'); });
log('done');
```

details:
  webmidi v2.0.0-rc.11
  Web MIDI browser v1.0.6
  iOS 11.2.1   iPad Air 2

**Comment by belm0** [comment]
I forgot to note that the Web MIDI Browser test app, which uses the Web MIDI API directly, works fine in both cases.

**Comment by belm0** [comment]
I have the web inspector running now and was able to narrow this down:  the promise for the open() call on the port corresponding to the bluetooth MIDI input is never completing.  This is the code added to enable() recently to ensure that all devices trigger connected event at init.

I can't confirm if this is specific to the device being bluetooth since I don't have the necessary cable to test USB connection to the iPad.

Interestingly, if I forcibly remove that promise from the subsequent Promise.all() call then things work fine, and the app still gets a connected event on the bluetooth MIDI input.

**Comment by cotejp** [comment]
Hmm. This is odd. There has to be a reason for the promise not being fulfilled. Can you try to with the [latest GitHub version](https://github.com/cotejp/webmidi/blob/master/src/webmidi.js) and tell me if you see a warning in the console.

**Comment by cotejp** [comment]
Since I haven't heard back from you, I'm going to close this as I have no means to test this scenario any further. You can always reopen it if you have more info to provide.
