### ISSUE TITLE
Nothing sends/receives with SysEx enabled

### ISSUE THREAD

**Issue by baconbrad** [cotejp/webmidi#29]
I am trying to send SysEx to a Novation launchpad.
```javascript
var output = WebMidi.getOutputByName("Launchpad MK2");
output = WebMidi.outputs[0];
output.sendSysex([0x00, 0x20, 0x29], [1, 2, 3, 4, 5]);
```
Results in `Error: SysEx message support must first be activated.`

I set `{ sysex: true }` in `WebMidi.enable()`. (This was a guess) Chrome prompted me to enable the permission which I did. Now MIDI doesn't work at all until I remove the option.

Full code:
```javascript
WebMidi.enable({ sysex: true }, function (err) {
  if (err) {
    console.log("WebMidi could not be enabled.", err);
  } else {
    var input = WebMidi.getInputByName("Launchpad MK2");
    input = WebMidi.inputs[0];
    input.addListener('noteon', "all", function (e) {
      console.log(e);
    });
    input.addListener('noteoff', "all", function (e) {
      console.log(e);
    });
    var output = WebMidi.getOutputByName("Launchpad MK2");
    output = WebMidi.outputs[0];
    output.sendSysex([0x00, 0x20, 0x29], [1, 2, 3, 4, 5]);
  }
});
```

Maybe am I just not using this correctly?

**Comment by cotejp** [comment]
This is how you activate it:

```javascript
WebMidi.enable(function (err) {
  // code here
}, true);
```
More details can be found in the [API documentation](http://cotejp.github.io/webmidi/latest/classes/WebMidi.html#method_enable). 

Cheers!

**Comment by baconbrad** [comment]
Thanks, for the quick reply. That explains it. Works as expected now.

**Comment by baconbrad** [comment]
Unrelated but I am very happy to figure out this part all by myself using the webmidi.js documentation and Launchpad programmers guide. This flashes "Hello world!" on the Launchpad. Thank you for webmidi.js!
```javascript
output.sendSysex([0x00, 0x20, 0x29], [0, 4, 20, 124, 1, 5, 72, 101, 108, 108, 111, 32, 2, 119, 111, 114, 108, 100, 33]);
```

**Comment by cotejp** [comment]
I haven't used sysex much myself... Glad it works for you!
