### ISSUE TITLE
Web MIDI Api for Firefox

### ISSUE THREAD

**Issue by jazz-soft** [cotejp/webmidi#30]
Not an issue, rather a good news:
There is a Web MIDI API extension for Firefox available at https://addons.mozilla.org/en-US/firefox/addon/web-midi-api
Please check it out!

**Comment by cotejp** [comment]
That's great news! I installed the Jazz-Midi extension and the Web MIDI API extension in Firefox and it seems to be working. I'll have to do some more tests but, so far so good!

Thanks for notifying me. Cheers!

**Comment by cotejp** [comment]
I've updated the README with all relevant info.
