### ISSUE TITLE
Trouble with sendClock()

### ISSUE THREAD

**Issue by jmichaelprobert** [cotejp/webmidi#31]
I'm having trouble getting sendClock to work. 

I'm sure that it's an issue on my formatting but I can't seem to get it to work. 

I've had success with sending control changes and program changes though.

Here's what I've tried to help set me straight: 

output.sendClock(output={time="+1000"})
output.sendClock(output={"time"="+1000"})
output.sendClock(output={"time": "+1000"})
output.sendClock({time="+1000"})
output.sendClock(output={"+1000"})

I just need some help getting the syntax right. I'm attempting to get convert BPM to MS to set the value on a delay pedal.

Love this project! I'm trying to make an editor for my midi devices that I can save settings on my laptop and then dump them onto my devices as needed.

**Comment by jmichaelprobert** [comment]
Accidentally added my comment before completing my description, it's fully there now.

**Comment by cotejp** [comment]
The `sendClock()` method accepts a single optional parameter which is an object litteral. This is a very common approach in JavaScript. Here's how you would use it:

 ```javascript
output.sendClock({time: "+1000"})
```

**Comment by cotejp** [comment]
@jmichaelprobert Since I haven't heard back, I'm assuming it is now working for you. I'm going to close this issue. If you still have a problem, you can always reopen it.
