### ISSUE TITLE
How to cause a SYSEX permission request on Chromium?

### ISSUE THREAD

**Issue by hires** [cotejp/webmidi#32]
Thanks for this awesome library! I've been working on a patch editor that requires SYSEX access. The examples work for channel messages but when I try enable with SYSEX support in Chromium I just get an error. I've turned on the option to allow requests for SYSEX access.

I've tried both WebMidi.enable() as well as navigator.requestMIDIAccess() which I saw somewhere else and neither seem to work.

Any help would be greatly appreciated! My project is basically impossible if I can't send SYSEX.

**Comment by cotejp** [comment]
Thanks for reporting this. There indeed was a problem with the parsing of sysex messages. Can you try v2.0.2 and tell me if it fixes your problem?

**Comment by cotejp** [comment]
> However in Chromium, when I try to send MIDI I get the error: "Uncaught Error: SysEx message support must first be activated."

You must pass a 2nd argument (`true`) to `WebMidi.enable()` in order to activate sysex support. This is required by the Web MIDI API:

```javascript
WebMidi.enable(function (err) {
  // your code here
}, true);
```
It is kind of hard to help you without seeing your code. Do you have a simple code sample that triggers the problem?

**Comment by hires** [comment]
I'm doing as you say. Here is my code:

    WebMidi.enable(function(err) {
        if(err) {
            console.log("WebMidi cannot be enabled!");
        }
        else {
            console.log("WebMidi enabled!");
            // create dropdown for MIDI output select
            let controls = document.getElementById("controls");
            let select = document.createElement("select");
            select.id = "midiOut";
            select.setAttribute("onchange", "midiPortSelect(this.value)");
            controls.appendChild(select);
            for(i = 0; i < WebMidi.outputs.length; i ++) {
                console.log("output: " + WebMidi.outputs[i].name);
                let option = document.createElement("option");
                option.appendChild(document.createTextNode(WebMidi.outputs[i].name));
                select.appendChild(option);
            }
        }
    }, true);

**Comment by cotejp** [comment]
Your code works for me on Chrome/macOS. If you say that you cannot get `navigator.requestMIDIAccess()` to work, this means that the problem is probably upstream (in Chrome itself). I'll try to find a Linux device to try it on...

**Comment by hires** [comment]
It turns out that, at least on Linux, Chrome and Chromium will not allow SYSEX access unless the app is served over HTTPS! This was the push I needed to actually install Let's Encrypt on my webserver and sure enough, right away I get the pop-up and my test worked. (I sent a reboot command to one of my modules)

Maybe a few more notes on the instructions page would help others avoid the confusion about this. Thanks again!

**Comment by cotejp** [comment]
> Maybe a few more notes on the instructions page would help others avoid the confusion about this. 

I updated the README and the API documentation. Thanks!
