### ISSUE TITLE
Add musical instruments to play music in realtime

### ISSUE THREAD

**Issue by surikov** [cotejp/webmidi#33]
Add musical instruments from WebAudioFonts.

It includes samples from Fluid, General User GS etc. Pianos, guitars, Fx, about 2000 instruments and drums.
See example at
https://surikov.github.io/webaudiofont/examples/dynamic.html

**Comment by cotejp** [comment]
Thanks for your suggestion. However, in the spirit of keeping the library well-focused, I think it's more appropriate for WebMidi.js to keep concentrating on what it does best: MIDI communication. 

Your WebAudioFont project is very interesting and I'm sure it could be used alongside WebMidi.js. You have to remember that not everybody using WebMidi.js will need sounds. Most users actually just need to interface with other hardware and software.

Cheers!
