### ISSUE TITLE
Issue with MidiNote 0 (does not have octave attribute)

### ISSUE THREAD

**Issue by Enteleform** [cotejp/webmidi#34]
I just wrote a script to test WebMIDI with my devices and noticed that the `event.note.octave` attribute of `MidiNote{value:0, name:C, octave:-2}` returns `undefined` when accessed from the listener callback.

Tested with:
- Akai APC Mini
- Akai MPK 249 with octave modifier set to minimum
![webmidi apc issue](https://user-images.githubusercontent.com/10906415/39419618-a5c66d80-4c2e-11e8-877e-25d9ef21ba3d.png)

&nbsp;  
### demo.ts
```javascript
WebMidi.enable( function(error){
  if(error)
    {console.log("WebMidi Error:", error)}

  for(input of WebMidi.inputs){
    input.addListener(
      /* type     */ "noteon",
      /* channel  */ "all",
      /* callback */  function(event){console.log(`NoteOn:  ${event.note.name}${event.note.octave}`)}
    )
    input.addListener(
      /* type     */ "noteoff",
      /* channel  */ "all",
      /* callback */  function(event){console.log(`NoteOff: ${event.note.name}${event.note.octave}`)}
    )
    input.addListener(
      /* type     */ "controlchange",
      /* channel  */ "all",
      /* callback */  function(event){console.log(`CC:      ${event.controller.number}.${event.value}`)}
    )
  }
})
```

&nbsp;  
### Output
```xml
NoteOn:  Cundefined
NoteOff: Cundefined
NoteOn:  C#-2
NoteOff: C#-2
NoteOn:  D-2
NoteOff: D-2
```

**Comment by cotejp** [comment]
Thanks a lot for reporting this! The problem has been fixed in [2.0.5](https://github.com/cotejp/webmidi/releases/tag/2.0.5) which is available now on [npm](https://www.npmjs.com/package/webmidi).
