### ISSUE TITLE
MIDIMessageEvent.receivedTime is deprecated

### ISSUE THREAD

**Issue by 1j01** [cotejp/webmidi#5]
In Chrome: "MIDIMessageEvent.receivedTime is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/5665772797952000 for more details."

**Comment by cotejp** [comment]
Reference to `MIDIMessageEvent.receivedTime` have been removed in [v2.0.0-beta1](https://github.com/cotejp/webmidi/releases/tag/2.0.0-beta.1) as per the upstream change in Chrome. There is no point in letting this linger in what is currently a beta version.

Thanks @1j01 for pointing this out.
