### ISSUE TITLE
output.playNote("C3") doesn't make any ksound

### ISSUE THREAD

**Issue by soichih** [cotejp/webmidi#7]
I am trying to see if this works on Chrome, and I did following

```
    WebMidi.enable(function (err) {
      if (err) {
        console.log("WebMidi could not be enabled.", err);
      } else {
        console.log("WebMidi enabled!");
        var mout = WebMidi.outputs[0];
        var mout.playNote("C3");
      }
    });
```

It doesn't make any sound. Do I need to set volume, instrument, etc?

* I don't have any MIDI instrument attached to my computer. I am trying to play sounds just using a browser.

**Comment by soichih** [comment]
Sorry, I think I should be using soundfont-player instead.. (https://www.npmjs.com/package/soundfont-player)

**Comment by cotejp** [comment]
The `playNote()` method sends **note on** commands to the output it is called upon. The output must be a software or hardware MIDI device recognized by your system. It is that device that will play the sound, not WebMidi.js. But, considering your second message, I guess you figured that out! :-)
