### ISSUE TITLE
Add 'all' note option to Output.prototype.stopNote 

### ISSUE THREAD

**Issue by drewm** [cotejp/webmidi#8]
The first param to `Output.prototype.stopNote` is a note number or name. It would be convenient to have an `all` option which effectively would be the same as

```
output.stopNote([0, 1, 2, ..., 127]);
```

The `all` option is used elsewhere for channels, so it would feel consistent. 

This option would be useful when you've got yourself into a mess with lots of notes on and need to switch them off, perhaps due to buggy code.

If you like the idea, I'm happy to implement and submit a pull request.

**Comment by cotejp** [comment]
This makes a lot of sense! We should be using the **all notes off** channel mode message so we don't unnecessarily flood the device with 128 different messages for each channel:

`Output.sendChannelMode("allnotesoff", 0, channel, options)`

If you're willing to take a stab at it, that would be great!

**Comment by cotejp** [comment]
Available in [2.0.0-rc.3](https://github.com/cotejp/webmidi/releases/tag/2.0.0-rc.3). 
Thanks @drewm
